Dashboard/Controllers/FilterController.cs
using Dashboard.Models;
using Dashboard.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Reflection.Metadata;

namespace Dashboard.Controllers
{
    public class FilterController : Controller
    {
        public FilterRepositories _filterRepositories;
        public FilterController(FilterRepositories filterRepositories)
        {
            _filterRepositories = filterRepositories;
        }
        public IActionResult Index(string type, string modulename,string control,string input)
        {
            var result =  _filterRepositories.FilterImp(type,modulename, control, input);
            return View(result);
        }
        #region API CALLS
        [HttpGet]
        public IActionResult GetAll(string type, string modulename, string control, string input)
        {
            var result = _filterRepositories.FilterImp(type, modulename, control, input);
            var data = result;
            return Json(new { data });
        }
        #endregion

    }
}

Dashboard/Controllers/JsontoexcelController.cs
using ClosedXML.Excel;
using Dashboard.Models;
using DocumentFormat.OpenXml.Features;
using DocumentFormat.OpenXml.Spreadsheet;
using Grpc.Core;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Data;
using System.Reflection;

namespace Dashboard.Controllers
{
    public class JsontoexcelController : Controller
    {
        public IActionResult Index()
        {
            //return View();
            return View();
        }

        [HttpPost]
        public IActionResult ConvertJsonTextToExcel(string jsonData)
        {
            var data = JsonConvert.DeserializeObject<List<JsonToExcelTextModel>>(jsonData);
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add("Data");

                worksheet.Cells["A1"].LoadFromCollection(data, true);

                Response.Headers["Content-Type"] = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.Headers["Content-Disposition"] = "attachment; filename=ExcelDoc3.xlsx";

                Response.Body.Write(package.GetAsByteArray());
            }

            return new EmptyResult();
        }
        [HttpPost]
        public IActionResult ConvertJsonToExcel(string jsondata)
        {
             DateTime currentDateTime = DateTime.Now;
            string formattedDateTime = currentDateTime.ToString("yyyyMMddHHmmss");
            JsonToExcelTextModel model = new JsonToExcelTextModel();
            model.data = new Data();
            byte[] excelFile;
            bool temp = false;
            bool loginCountStatus = false;
            bool userLoginStatus = false;
            bool entry = false;
            // Counter to track the number of rows
            int rowCount = 0;
            List<ClientModel> data = new List<ClientModel>();

            model = JsonConvert.DeserializeObject<JsonToExcelTextModel>(jsondata);

            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            DataTable dt = new DataTable();
            dt.Columns.Add("Message", typeof(string));
            dt.Columns.Add("Status", typeof(string));
            dt.Columns.Add("TotalUser", typeof(string));
            dt.Columns.Add("IOSUser", typeof(string));
            dt.Columns.Add("Androidusers", typeof(string));
            dt.Columns.Add("Otherusers", typeof(string));
            dt.Columns.Add("Client Type Sum", typeof(string));
            dt.Columns.Add("Login Count Sum", typeof(string));
            dt.Columns.Add("Name", typeof(string));
            dt.Columns.Add("Mobile", typeof(string));
            dt.Columns.Add("UCC", typeof(string));
            dt.Columns.Add("Client Type", typeof(string));
            dt.Columns.Add("Login Count", typeof(string));
            dt.Columns.Add("Event Time", typeof(string));
            dt.Columns.Add("User IP", typeof(string));
            dt.Columns.Add("Device Info", typeof(string));
            dt.Columns.Add("Model", typeof(string));
            dt.Columns.Add("UUID", typeof(string));

            // For header modification first added empty row
            for (int i = 0; i < 3; i++)
            {
                if (rowCount < 3)
                {
                    // Modify header values as needed
                    dt.Rows.Add(); // Add an empty row for header modification
                    rowCount++; // Reset the counter for data rows
                }
            }

            foreach (var userDetail in model.data.userdetails)
            {
                string message = model.message;
                string status = model.status.ToString();
                string totaluser = model.data.totaluser.ToString();
                string iosusers = model.data.iosusers.ToString();
                string androidusers = model.data.androidusers.ToString();
                string otherusers = model.data.otherusers.ToString();
                string name = userDetail?._name;
                string mobile = userDetail?._mobile;
                string ucc = userDetail?.ucc;
                string clientType = userDetail?.clienttype;
                string loginCount = userDetail?.userlogincount.ToString();
                loginCountStatus = false;

                foreach (var deviceDetail in userDetail.userloggeddevicedetails)
                {
                    string eventTime = deviceDetail.eventtime?.ToString();
                    string userIp = deviceDetail?.userip;
                    string deviceinfo = deviceDetail?.deviceinfo;
                    string modelinfo = deviceDetail?.model;
                    string uuid = deviceDetail?.uuid;
                    entry = false;
                    userLoginStatus = false;
                    if (model.message != null && temp == false)
                    {

                        dt.Rows.Add(message, status, totaluser, iosusers, androidusers, otherusers, "","",name, mobile, ucc, clientType, loginCount, eventTime, userIp, deviceinfo, modelinfo, uuid);
                        temp = true;
                        loginCountStatus = true;
                        userLoginStatus = true;
                        entry = true;
                        
                    }
                    if(temp == true && loginCountStatus == false && userLoginStatus == false &&entry == false)
                    {
                        dt.Rows.Add("", "", "", "", "", "", "", "", name, mobile, ucc, clientType, loginCount, eventTime, userIp, deviceinfo, modelinfo, uuid);
                        
                        loginCountStatus = true;
                        userLoginStatus = true;
                        //entry = false;
                        

                    }
                    if (temp == true && loginCountStatus == true && userLoginStatus == false && entry == false)
                    {
                        dt.Rows.Add("", "", "", "", "", "", "", "", "", "", "", "", "", eventTime, userIp, deviceinfo, modelinfo, uuid);
                        //entry = false;
                        //loginCountStatus = true;
                        
                    }
                }
            }

            int skippedRows = 0;
            foreach (DataRow row in dt.Rows)
            {
                
                if (skippedRows < 3)
                {
                    skippedRows++;
                    continue; // Skip processing of the first 4 rows
                }
               
                    var a = row[11];
                    var b = row[12];
                    if (row[11] != "" && row[12] != "")
                    {
                        ClientModel data1 = new ClientModel()
                        {
                        ClientTypeSum = row[11].ToString(), LoginCountSum = Convert.ToInt32(row[12])
                        };
                        data.Add(data1);
                    }
            }

            var summedData = data
            .GroupBy(item => item.ClientTypeSum)
            .Select(group => new ClientModel
            {
                ClientTypeSum = group.Key,
                LoginCountSum = group.Sum(item => item.LoginCountSum)
            })
            .ToList();
            var tempdata = summedData;

            //int skippedRows2 = 0;
            int valinc = 3;
            foreach (var val in summedData)
            {
                    dt.Rows[valinc][6] = val.ClientTypeSum;
                    dt.Rows[valinc][7] = val.LoginCountSum.ToString();
                    valinc++;
                
            }


            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add("Data");
                worksheet.Cells["A1"].LoadFromDataTable(dt, true);
                // Define parent and child headers

                // Get the entire range of cells (including both header and data cells)
                var entireRange = worksheet.Cells[1, 1, 3, dt.Columns.Count + 1];

                // Apply horizontal and vertical center alignment to the entire range
                entireRange.Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
                entireRange.Style.VerticalAlignment = ExcelVerticalAlignment.Center;

                //data field make tje center
                var dataRange = worksheet.Cells[4, 1, dt.Rows.Count + 1, 6];
                dataRange.Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;

                //Get the entire range of cells (including both header and data cells)
                var specifiedRange = worksheet.Cells[4, dt.Columns.Count - 4, 4, dt.Columns.Count + 1];

                // Apply horizontal and vertical center alignment to the entire range
                specifiedRange.Style.HorizontalAlignment = ExcelHorizontalAlignment.Left;

                worksheet.Cells["A1:A4"].Merge = true;
                worksheet.Cells["A1"].Value = "Message";
                worksheet.Cells["B1:B4"].Merge = true;
                worksheet.Cells["B1"].Value = "Status";
                worksheet.Cells["C1:R1"].Merge = true; // Merge cells for parent header
                worksheet.Cells["C1"].Value = "data";
                // Set child column headers
                worksheet.Cells["C2:C4"].Merge = true;
                worksheet.Cells["C2"].Value = "TotalUser";
                worksheet.Cells["D2:D4"].Merge = true;
                worksheet.Cells["D2"].Value = "IOSUser";
                worksheet.Cells["E2:E4"].Merge = true;
                worksheet.Cells["E2"].Value = "Androidusers";
                worksheet.Cells["F2:F4"].Merge = true;
                worksheet.Cells["F2"].Value = "Otherusers";
                worksheet.Cells["G2:G4"].Merge = true;

Dashboard/Controllers/MfpaymentController.cs
using Dashboard.DbService;
using Dashboard.Models;
using Dashboard.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace Dashboard.Controllers
{
    public class MfpaymentController : Controller
    {
        private readonly NpgsqlDbService _dbService;
        public MfpaymentRepositories _mfpaymentRepositories;
        MfpaymentModel mfpayment = new MfpaymentModel();
        public MfpaymentController(NpgsqlDbService dbService, MfpaymentRepositories mfpaymentRepositories)
        {
            _dbService= dbService;
            _mfpaymentRepositories= mfpaymentRepositories;
        }
        public IActionResult Index()
        {
            mfpayment.MfpaymentDataModel = _mfpaymentRepositories.MfpaymentImp(_dbService);
            return View(mfpayment);
        }
        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            mfpayment.MfpaymentDataModel = _mfpaymentRepositories.MfpaymentImp(_dbService);

            var data = mfpayment.MfpaymentDataModel;
            return Json(new { data });
        }
        #endregion
    }
}

Dashboard/Controllers/RequestRespController.cs
using Dashboard.DbService;
using Dashboard.Models;
using Dashboard.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Dashboard.Controllers
{
    public class RequestRespController : Controller
    {
        private readonly NpgsqlDbService _dbService;
        public RequestRepositoriesImp _requestRepositories;
        RequestModel requestModel = new RequestModel();
        public FilterRepositories _filterRepositories;

        public RequestRespController(NpgsqlDbService dbService,RequestRepositoriesImp requestRepositories, FilterRepositories filterRepositories)
        {
            _dbService = dbService;
            _requestRepositories = requestRepositories;
            _filterRepositories = filterRepositories;
        }
        
        public IActionResult Index(string query)
        {
            requestModel.RequestDataModel = _requestRepositories.requestImp(_dbService);
            requestModel.RequestListModel = _requestRepositories.requestListImp(_dbService);
            return View(requestModel);
        }

        public IActionResult TopRequest(string query)
        {

            requestModel.RequestDataModel = _requestRepositories.requestImpFilter(_dbService).OrderByDescending(x => x.requestedon).Take(5).ToList();
            return View(requestModel);
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll(string status)
        {
            requestModel.RequestDataModel = _requestRepositories.requestImp(_dbService);
            switch (status)
            {
                case "topRequest":
                    requestModel.RequestDataModel = _requestRepositories.requestImpFilter(_dbService).OrderByDescending(x => x.requestedon).Take(5).ToList();
                    break;
                default:
                    break;
            }
            var data = requestModel.RequestDataModel;
            return Json(new { data });
        }
        #endregion
    }
}

Dashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dashboard</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Dashboard.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
</head>
<body>
    <header >
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">RISE Dashboard</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                     
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class=" float-end">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class=" float-end">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                        <li class="nav-item dropdown ">
                            @*<a class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Logs</a>*@
                            <button class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" onclick="toggledropdown()">
                                Logs
                            </button>
                            <ul class="dropdown-menu dropdown-menu-dark" id="dropcontainer">
                                        <li><a class="dropdown-item" id="apis" name="apis" asp-area="" asp-controller="RequestResp" asp-action="Index" >Apis</a></li>
                                <li>
                                    <a class="dropdown-item" id="exceptions" name="exceptions" asp-area="" asp-controller="ExceptionData" asp-action="Index" >Exceptions</a>
                                </li>
                                   <li><a class="dropdown-item" id="insertqueries" asp-area="" asp-controller="InsertQuery" asp-action="Upload">InsertQuery</a>
                                </li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Mfpayment" asp-action="Index">MF Payments</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="" asp-action="">US Payments</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="" asp-action="">User Management</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="" asp-action="">Data Sanity</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Jsontoexcel" asp-action="Index">jsontoexcel</a></li>
                            </ul>
                        </li>
                        
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Links</a>
                            <div class="dropdown-menu dropdown-menu-dark">
                                <a class="dropdown-item" asp-area="" asp-controller="" asp-action="">Figma</a>
                                <a class="dropdown-item" asp-area="" asp-controller="" asp-action="">BRS</a>
                                <a class="dropdown-item" asp-area="" asp-controller="" asp-action="">API Design Doc</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">API</a>
                            <div class="dropdown-menu dropdown-menu-dark">
                                <a class="dropdown-item" asp-area="" asp-controller="" asp-action="">Search API</a>
                                <a class="dropdown-item" asp-area="" asp-controller="" asp-action="">Search Mapping</a>
                                <a class="dropdown-item" asp-area="" asp-controller="" asp-action="">Add API</a>
                                <a class="dropdown-item" asp-area="" asp-controller="" asp-action="">Add Mapping</a>
                                <a class="dropdown-item" mo-area="" asp-controller="" asp-action="">Test Vendor API</a>
                            </div>
                        </li>
                    </ul>
                   @* <form action="@Url.Action("Index", "RequestResp")" method="get" class="d-flex">
                        <i class="bi bi-search"></i>
                        <input class="form-control me-2"  type="text" name="query" placeholder="Search" aria-label="Search">
                        <button type="submit" class="btn btn-default">Search</button>
                        <button type="submit"></button>
                    </form>*@
                </div>
                
                
            </div>
        </nav>
    </header>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top bg-dark footer  text-white">
        <div class="container ">
            &copy; 2023 - RISE Dashboard - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Dashboard/Views/Shared/_filterLogic.cshtml
@*
@using (Html.BeginForm("Index", "Filter", FormMethod.Get))
{
    <div class="input-container">
        <input type="text" id="apps" name="type" placeholder="Types">
        <input type="text" name="modulename" placeholder="ModuleName">
        <input type="text" name="control" placeholder="Control">
        <input type="text" name="input" placeholder="Input">
        <input type="submit" value="Filter">
    </div>
}

<script>
    //document.getElementById("apps").value = "Apis";

    /*var liquor_selected = document.querySelector('#dropcontainer');
    var selected = liquor_selected.addEventListener('click', function (e) {
        if(liquor_selected.getElementsByClassName("apis"))
        {
        document.getElementById("apps").value = "Apis"
        }
        if (liquor_selected.getElementsByClassName("exceptions")) {
            document.getElementById("apps").value = "Exceptions"
        }
});*/
    function toggledropdown() {
        var dropdown = document.getElementById('dropcontainer');

        var  output = dropdown.value;

        if (output == "Apis") {
            document.getElementById("apps").value = "Apis"
        }
        if (output == "Exceptions") {
            document.getElementById("apps").value = "Exceptions"
        }
        
    
</script>
*@